import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const products = [
      { id: 1, 
        name: 'RE501RM drift box R MIDI',
         description: 'analogue synthesizer SSP',
         price:399, 
        details: ['All analogue circuits',
                 '2 VCOs 0.1 -10KHz sweep',
                 '24dB low-pass filter',
                 'AR D/S envelope generator',
                 'OSC sync and X-MOD',
                 'Pitch EG MOD','MIDI key trigger, pitch and porta control',
                 'Dual voice'],   
        available:"Now",
        youtubeurl:"https://www.youtube.com/embed/MnP0coCfNaM",
         photo1:'/images/RE501RM_Blue/RE501RM_Angle.jpg',
         photo2:'/images/RE501RM_Blue/RE501RM_Front.jpg',
         photo3:'/images/RE501RM_Blue/RE501RM_Rear.jpg',
         photo4:'/images/RE501RM_Blue/RE501RM_Top.jpg'},

      { id: 2, 
        name: 'RE501SE drift box SE',
        description: 'analogue synthesizer SSP',
        price:399, 
        details: ['4-voice dual DCOs',
                  '6 waveform types',
                  '12dB Steiner low-pass filter',
                  'Selectable AD/ASR with reverse mode',
                  'OSC X-MOD and hard sync ',
                  'Pitch EG MOD',
                  'Joystick cross modulation control',
                  'MIDI IN, CV/GATE IN'], 
        available:"Oct 2018",
       youtubeurl:"https://www.youtube.com/embed/qFA4lWt_Vjo",   
         photo1:'/images/RE501SE_Brown/RE501SE_Angle.jpg',
         photo2:'/images/RE501SE_Brown/RE501SE_Front.jpg',
         photo3:'/images/RE501SE_Brown/RE501SE_Rear.jpg',
         photo4:'/images/RE501SE_Brown/RE501SE_Top.jpg'},

      { id: 3,
       name: 'RE501S drift box S ',
        description: 'rev2 analogue synthesizer SSP ',
         price:389, 
         details: ['All analogue circuits',
                  '2 VCOs 0.1 -10KHz sweep',
                  '24dB Rudder-type low-pass filter',
                  'OSC X-MOD',
                  'Joystick cross modulation control',
                  'CV/GATE IN'], 
        available:"Nov 2018",
        youtubeurl:"https://www.youtube.com/embed/0FUkGJ8Ltb0",
         photo1:'/images/RE501S_Orange/RE501S_Angle.jpg',
         photo2:'/images/RE501S_Orange/RE501S_Front.jpg',
         photo3:'/images/RE501S_Orange/RE501S_Rear.jpg',
         photo4:'/images/RE501S_Orange/RE501S_Top.jpg'},

      { id: 4,
       name: 'RE501J drift box J', 
       description: 'joystick controller sequencer SSP',
        price:379,
        details: [['2 joystick VCA control'], [
                      'X/Y axis dual CV',
                      '2 channel manual CV control and CV attenuation',
                      '2 channel programmable CV',
                      'sequence output'],
                  '16 step programmable sequencer',
                  'MIDI slave sync mode',
                  'GATE sync master/slave mode'],
         available:"Nov 2018",
         youtubeurl:"",
         photo1:'/images/RE501J_Yellow/RE501J_Angle.jpg',
         photo2:'/images/RE501J_Yellow/RE501J_Front.jpg',
         photo3:'/images/RE501J_Yellow/RE501J_Rear.jpg',
         photo4:'/images/RE501J_Yellow/RE501J_Top.jpg'
       },

      { id: 5,
       name: 'RE501C drift box C',
       description: 'programmable audio/CV mixer  SSP',
       price:349,
       details: ['4 channel, selectable CV/audio mode',
                  'Individual L/R level control per channel',
                  '8 memory scene recall',
                  'Memory bank step thru via GATE signal',
                  'GATE OUT multi-link',
                  'MUTE and attenuating switches',
                  'Headphone output'],
         available:"Nov 2018",
         youtubeurl:"https://www.youtube.com/embed/AGGTHmShcg0",
         photo1:'/images/RE501C_Purple/RE501C_Angle.jpg',
         photo2:'/images/RE501C_Purple/RE501C_Front.jpg',
         photo3:'/images/RE501C_Purple/RE501C_Rear.jpg',
         photo4:'/images/RE501C_Purple/RE501C_Top.jpg'},

      { id: 6,
        name: 'RE501W drift box W',
        description: 'multi-modulation analog synthesizer SSP',
        price:430, 
        details: ['All analogue circuits',
                '5 joystick control with CV output',
                '2 VCOs 0.1 -10KHz sweep',
                '24dB low-pass filter',
                'Dual wave LFO crossfade',
                'Analogue delay with joystick feedback control'],
        available:"TBC",
        youtubeurl:"",
         photo1:'/images/RE501W_Silver/RE501W_Angle.jpg',
         photo2:'/images/RE501W_Silver/RE501W_Front.jpg',
         photo3:'/images/RE501W_Silver/RE501W_Rear.jpg',
         photo4:'/images/RE501W_Silver/RE501W_Top.jpg'},
    ];
    return {products};
  }
}